from .registration_form import RegistrationForm
from .login_form import LoginForm
from .stock_actions import StockActions
from .information import Information
from .depot_history import DepotHistory
from .financial_history import FinancialHistory
from .bank_transfer import BankTransfer
from .depot_settings_form import SettingsForm
from .validation import Validation
from .watchlist import Watchlist
from .depot_welcome import Welcome
